### PR TITLE
fix for issue #6

### PR DESCRIPTION
**Pull request by nestoru**
Thanks again for this plugin. I felt the obligation to contribute rather than just ask. Best, - Nestor

### CODE REVIEW

**Comment by daviddengcn** [comment]
Thanks for the pull-request. Setting the "word-break" attribute is absolutely necessary.

Per using the relative size (100% for the table) other than the absolute pixels, there are pros and cons and I made a decision of using the absolute pixels. The main concerns of using relative size:

1) For monitors of very high resolution, since quite a few code (this tool was designed to show diff of Java code at the very beginning) are formatted to contain no lines of more than 80 chars. There'll be a blank between the left code and the right code, which makes the diff harder to read.
2) For monitors of very low resolution, the line will be wrapped, which is also bad for reading the diff.

So, I suggest we set the "word-break" attribute only and remain other things unchanged.

Your thoughts?

**Comment by nestoru** [comment]
Hi David,

Thanks for getting back to me on this.  In cases like ours, fix sizes even though good enough it won't be ideal. This is because (back to your points):
1. If you have really long lines like in our case (when using Talend open source) then using fix width will actually force you to use less of the available real estate. I see more information with relative size than with fix size in a MBP 15 inches using 1680x1050. I would argue that if I have big monitor / resolution I would not maximize screens unnecessarily. But even with shorter lines you have a problem with fix positioning: there will be too much space on the left pane that can't be resized. With relative size left and right can be adjusted as needed fulfilling any needs. After all that is what responsiveness means, right?
2. Developers do not use low resolutions for graphical tools (like Talend which is not any different than Eclipse for programing in Java) where hundreds of visual components are rendered and the more you are able to see the better. I don't think we should worry about low resolutions like 800x600.

Perhaps we could make doRender() to read an option to render fixed or relative modes?

Cheers and thanks again for your plugin!

- Nestor

**Comment by daviddengcn** [comment]
I'm OK with an option of how the result page is organized. The default
setting will use an automatic algorithm: If there are lines longer than 100
chars, switch to relative width and word breaking mode.

Two other options are "fixed width" and "responsive width".

**Comment by nestoru** [comment]
Sounds great! Thanks a lot in advance.

**Comment by daviddengcn** [comment]
I've updated the extension in Chrome store to 1.8 with auto selection of relative/fixed width. Let me know if an explicit option is still necessary.

**Comment by daviddengcn** [comment]
Sorry, will not merged.

**Pull request closed without merging**
